/**
 * Shared helpers for the PDF / EPUB exporters: book metadata, page ordering
 * (mirrors the Starlight sidebar), and a local preview-server lifecycle.
 */
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';

export const BOOK_TITLES = {
  admin: 'grommunio Administration',
  guides: 'grommunio Setup Guides',
  cli: 'grommunio Command-line Reference',
  user: 'grommunio User Guide',
  web: 'grommunio Web',
  migration: 'grommunio Migration Guide',
  kb: 'grommunio Knowledge Base',
  man: 'grommunio Man Pages',
  dev: 'grommunio Developer Guide',
};

/** Parse the minimal frontmatter we need (title + sidebar.order). */
export function frontmatter(file) {
  const s = fs.readFileSync(file, 'utf8');
  const m = s.match(/^---\n([\s\S]*?)\n---/);
  const fm = { title: path.basename(file).replace(/\.mdx?$/, ''), order: 50 };
  if (m) {
    const t = m[1].match(/^title:\s*(.+)$/m);
    if (t) fm.title = t[1].trim().replace(/^["']|["']$/g, '');
    const o = m[1].match(/order:\s*(-?\d+)/);
    if (o) fm.order = parseInt(o[1], 10);
  }
  return fm;
}

// Sub-directories of a book are appended after its top-level pages, in the
// order the sidebar presents them (astro.config.mjs); anything not listed here
// follows alphabetically. Previously only top-level files were exported, so the
// Developer Guide PDF/EPUB lacked the Gromox specs, wiki and project pages and
// the CLI book lacked every grommunio-admin sub-command page.
const SUBDIR_ORDER = {
  dev: ['gromox', 'wiki', 'projects'],
  cli: ['grommunio-admin'],
};

/** Pages of one directory (non-recursive), sorted like Starlight's autogenerated sidebar. */
function pagesIn(dir, urlPrefix) {
  return fs.readdirSync(dir)
    .filter((f) => /\.mdx?$/.test(f))
    .map((f) => {
      const fm = frontmatter(path.join(dir, f));
      // Starlight lower-cases file names when it derives the route
      // (dev/wiki/Error-codes.md -> /dev/wiki/error-codes/).
      const base = f.replace(/\.mdx?$/, '').toLowerCase();
      const isIndex = base === 'index';
      return { slug: isIndex ? urlPrefix : `${urlPrefix}${base}/`, title: fm.title, order: fm.order, isIndex };
    })
    .sort((a, b) =>
      a.isIndex ? -1 : b.isIndex ? 1 : a.order - b.order || a.slug.localeCompare(b.slug),
    );
}

/** Ordered list of {slug,title} for a book, matching the sidebar order (sub-directories included). */
export function pagesFor(book, docsDir) {
  const dir = path.join(docsDir, book);
  const pages = pagesIn(dir, `/${book}/`);
  const preferred = SUBDIR_ORDER[book] ?? [];
  const subdirs = fs.readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort((a, b) => {
      const ia = preferred.indexOf(a), ib = preferred.indexOf(b);
      return (ia < 0 ? 1e9 : ia) - (ib < 0 ? 1e9 : ib) || a.localeCompare(b);
    });
  for (const sub of subdirs) pages.push(...pagesIn(path.join(dir, sub), `/${book}/${sub}/`));
  return pages;
}

function freePort() {
  return new Promise((res) => {
    const srv = net.createServer();
    srv.listen(0, () => { const p = srv.address().port; srv.close(() => res(p)); });
  });
}

// `astro preview` occasionally needs well over 30 s to answer its first request
// on a loaded machine (observed right after a PDF run), which made gen:epub abort
// with "preview server did not start in time"; allow 120 s.
async function waitFor(url, ms = 120000) {
  const t0 = Date.now();
  while (Date.now() - t0 < ms) {
    try { const r = await fetch(url); if (r.ok) return; } catch {}
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error('preview server did not start in time');
}

/**
 * Boot `astro preview` on a free port, run `fn(baseUrl)`, then shut it down.
 * Requires a prior production build (dist/).
 */
export async function withPreview(root, fn) {
  if (!fs.existsSync(path.join(root, 'dist'))) {
    throw new Error('No dist/ found — run `npm run build` first.');
  }
  const port = await freePort();
  const base = `http://localhost:${port}`;
  // Astro >= 7.2 manages `astro preview` through a lock file and, when it
  // detects an AI-agent/CI-like environment, daemonises the server: the spawned
  // process forks a background server and exits, so `server.kill()` killed
  // nothing, the orphan kept the lock, and every later run printed "Preview
  // server already running" and exited, leaving the exporter waiting on a port
  // nobody ever bound. Setting ASTRO_PREVIEW_BACKGROUND disables the agent
  // auto-detection (foreground server, as before), `--ignore-lock` keeps this
  // private instance out of the lock file, and the CLI is launched directly
  // (not via npx) so that `kill()` reaches the server process itself.
  const astroBin = path.join(root, 'node_modules/astro/bin/astro.mjs');
  const server = spawn(process.execPath, [astroBin, 'preview', '--port', String(port), '--ignore-lock'], {
    cwd: root,
    stdio: 'ignore',
    env: { ...process.env, ASTRO_PREVIEW_BACKGROUND: '0' },
  });
  try {
    await waitFor(base + '/');
    return await fn(base);
  } finally {
    server.kill('SIGTERM');
  }
}
